### ISSUE TITLE
rcl_lifecycle_transition type def is broken ?

### ISSUE THREAD

**Issue by hutualive** [Karsten1987/roscon2018#2]
Hi karsten, I'm new to ros and following your hands-on slides for roscon2018 to getting started.
I have installed ros2 from source following the github wiki with latest master branch source, under ~/ros2_ws of my ubuntu 18.04.
then cloned your repo for the hands-on, cd to ~/overlay_workspace, source ~/ros2_ws/install/setup.bash, colcon build.

I met the following errors:
-->
dp@dp:~/overlay_workspace$ source ~/ros2_ws/install/setup.bash
dp@dp:~/overlay_workspace$ colcon build
Starting >>> confbot_description
Starting >>> confbot_driver
Starting >>> confbot_sensors
Starting >>> confbot_tools
Finished <<< confbot_tools [1.80s]                                      
Finished <<< confbot_description [3.79s]                                  
--- stderr: confbot_sensors                                            
In file included from /home/dp/overlay_workspace/src/roscon2018/confbot_sensors/src/confbot_laser.cpp:1:0:
/home/dp/overlay_workspace/src/roscon2018/confbot_sensors/include/confbot_sensors/confbot_laser.hpp:50:3: error: ‘rcl_lifecycle_transition_key_t’ does not name a type; did you mean ‘rcl_lifecycle_transition_map_t’?
   rcl_lifecycle_transition_key_t
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   rcl_lifecycle_transition_map_t
/home/dp/overlay_workspace/src/roscon2018/confbot_sensors/include/confbot_sensors/confbot_laser.hpp:75:3: error: ‘rcl_lifecycle_transition_key_t’ does not name a type; did you mean ‘rcl_lifecycle_transition_map_t’?
   rcl_lifecycle_transition_key_t
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   rcl_lifecycle_transition_map_t
/home/dp/overlay_workspace/src/roscon2018/confbot_sensors/include/confbot_sensors/confbot_laser.hpp:85:3: error: ‘rcl_lifecycle_transition_key_t’ does not name a type; did you mean ‘rcl_lifecycle_transition_map_t’?
   rcl_lifecycle_transition_key_t
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   rcl_lifecycle_transition_map_t
/home/dp/overlay_workspace/src/roscon2018/confbot_sensors/include/confbot_sensors/confbot_laser.hpp:95:3: error: ‘rcl_lifecycle_transition_key_t’ does not name a type; did you mean ‘rcl_lifecycle_transition_map_t’?
   rcl_lifecycle_transition_key_t
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   rcl_lifecycle_transition_map_t
make[2]: *** [CMakeFiles/confbot_laser.dir/src/confbot_laser.cpp.o] Error 1
make[1]: *** [CMakeFiles/confbot_laser.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< confbot_sensors	[ Exited with code 2 ]
--- stderr: confbot_driver                                        
In file included from /home/dp/overlay_workspace/src/roscon2018/confbot_driver/src/twist_publisher.cpp:1:0:
/home/dp/overlay_workspace/src/roscon2018/confbot_driver/include/confbot_driver/twist_publisher.hpp: In member function ‘void confbot_driver::TwistPublisher::init()’:
/home/dp/overlay_workspace/src/roscon2018/confbot_driver/include/confbot_driver/twist_publisher.hpp:47:7: error: expected ‘;’ before ‘}’ token
       }
       ^
/home/dp/overlay_workspace/src/roscon2018/confbot_driver/include/confbot_driver/twist_publisher.hpp:49:5: error: expected ‘;’ before ‘}’ token
     }
     ^
In file included from /home/dp/overlay_workspace/src/roscon2018/confbot_driver/src/confbot_all.cpp:2:0:
/home/dp/overlay_workspace/src/roscon2018/confbot_driver/include/confbot_driver/twist_publisher.hpp: In member function ‘void confbot_driver::TwistPublisher::init()’:
/home/dp/overlay_workspace/src/roscon2018/confbot_driver/include/confbot_driver/twist_publisher.hpp:47:7: error: expected ‘;’ before ‘}’ token
       }
       ^
/home/dp/overlay_workspace/src/roscon2018/confbot_driver/include/confbot_driver/twist_publisher.hpp:49:5: error: expected ‘;’ before ‘}’ token
     }
     ^
make[2]: *** [CMakeFiles/twist_publisher.dir/src/twist_publisher.cpp.o] Error 1
make[1]: *** [CMakeFiles/twist_publisher.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/confbot_all.dir/src/confbot_all.cpp.o] Error 1
make[1]: *** [CMakeFiles/confbot_all.dir/all] Error 2
make: *** [all] Error 2
---
Aborted  <<< confbot_driver

Summary: 2 packages finished [8.71s]
  1 package failed: confbot_sensors
  1 package aborted: confbot_driver
  2 packages had stderr output: confbot_driver confbot_sensors
  1 package not processed

-->

I searched my ~, which have both ros2_ws and overlay_workspace, I do not find any type def matched with rcl_lifecycle_transition_key_t except for your source file(roscon2018/confbot_sensors/include/confbot_sensors/confbot_laser.hpp)

I changed to rcl_lifecycle_transition_map_t following the suggestion from build system, but still fail with error message:
--- stderr: confbot_sensors                                            
In file included from /home/dp/overlay_workspace/src/roscon2018/confbot_sensors/src/confbot_laser.cpp:1:0:
/home/dp/overlay_workspace/src/roscon2018/confbot_sensors/include/confbot_sensors/confbot_laser.hpp:51:3: error: conflicting return type specified for ‘virtual rcl_lifecycle_transition_map_t confbot_sensors::ConfbotLaser::on_configure(const rclcpp_lifecycle::State&)’
   on_configure(const rclcpp_lifecycle::State &)

what's wrong in the process to follow your slides ?

thanks in advance.

**Comment by Karsten1987** [comment]
@hutualive thanks for reporting. 
That's certainly my bad. I just pushed a [new commit](https://github.com/Karsten1987/roscon2018/commit/c684b75e35fa9756334f8874abafe1be8dd367a0) which complies to the latest ROS 2 master. The state as is got now tagged as `bouncy` which should work with the latest binary release.
Do you mind checking out the latest version of this repo and report back if this solves your problem?

**Comment by hutualive** [comment]
@Karsten1987 Great ! it's working now : )
though I spent a little bit time to make the rviz2 working as your slides(the shark marker and robot model are "hard" coded with your environment and absolute path.
thanks a lot for your prompt help.
