### ISSUE TITLE
How to solve ‘CallbackReturn’ in ‘class rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface’ does not name a type?

### ISSUE THREAD

**Issue by b2220333** [Karsten1987/roscon2018#3]
I build ROS2 bouncy by source code.

I run colcon build --cmake-args -DCMAKE_BUILD_TYPE=Debug

It shows:

Starting >>> confbot_description
Finished <<< confbot_description [0.52s]                   
Starting >>> confbot_driver
Finished <<< confbot_driver [0.91s]                        
Starting >>> confbot_sensors
--- stderr: confbot_sensors                              
In file included from /home/sam/ros2_overlay_ws/src/roscon2018/confbot_sensors/src/confbot_laser.cpp:1:0:
/home/sam/ros2_overlay_ws/src/roscon2018/confbot_sensors/include/confbot_sensors/confbot_laser.hpp:50:62: error: ‘CallbackReturn’ in ‘class rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface’ does not name a type
   rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn
                                                              ^
/home/sam/ros2_overlay_ws/src/roscon2018/confbot_sensors/include/confbot_sensors/confbot_laser.hpp:75:62: error: ‘CallbackReturn’ in ‘class rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface’ does not name a type
   rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn
                                                              ^
/home/sam/ros2_overlay_ws/src/roscon2018/confbot_sensors/include/confbot_sensors/confbot_laser.hpp:85:62: error: ‘CallbackReturn’ in ‘class rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface’ does not name a type
   rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn
                                                              ^
/home/sam/ros2_overlay_ws/src/roscon2018/confbot_sensors/include/confbot_sensors/confbot_laser.hpp:95:62: error: ‘CallbackReturn’ in ‘class rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface’ does not name a type
   rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn
                                                              ^
make[2]: *** [CMakeFiles/confbot_laser.dir/src/confbot_laser.cpp.o] Error 1
make[1]: *** [CMakeFiles/confbot_laser.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< confbot_sensors	[ Exited with code 2 ]

Summary: 2 packages finished [4.45s]
  1 package failed: confbot_sensors
  1 package had stderr output: confbot_sensors
  13 packages not processed

How to solve it?

Thank you~

**Comment by Karsten1987** [comment]
Are you sure that you're using the right tag of it?
There is a bouncy version for this repo: https://github.com/Karsten1987/roscon2018/tree/bouncy

Let me know if this works. The master branch of this repo aims for the latest master branch of ROS2.

**Comment by b2220333** [comment]
Oh, am I missing something?
I previously use git clone https://github.com/Karsten1987/roscon2018.git
And if I use open https://github.com/Karsten1987/roscon2018/tree/bouncy by firefox
It also shows https://github.com/Karsten1987/roscon2018.git to let me git clone.
What can I do next?
Thank you~

**Comment by Karsten1987** [comment]
Sorry, I guess I should have been a little more precise.

Git can work with tags, which are just persistent aliases for a commit hash. So we have one commit (a.ka. tag "bouncy") version of it which works for the latest bouncy release. Given that the current master of ROS2 has a slightly updated API for the lifecycle nodes, the current master commit of this repo here works only with the latest master of ROS2.

In your case, you're building this repo against ROS2 bouncy. Given the above explanation, you ought to checkout the "bouncy" tag of this repo. In order to do so, you can follow the steps below:

```
$ cd workspace/src
$ git clone https://github.com/Karsten1987/roscon2018.git
$ cd roscon2018
$ git checkout tags/bouncy -b bouncy
```

Alternatively, github also allows you to download a zip file of these tagged versions:
https://github.com/Karsten1987/roscon2018/releases

**Comment by b2220333** [comment]
Wow! Great~~
Very thanks for detailed explaination and the instructions that helps me a lot.
It works!!
