### ISSUE TITLE
flooding /cmd_vel with 0s doesnt stop the robot anymore

### ISSUE THREAD

**Issue by mikaelarguedas** [Karsten1987/roscon2018#46]
Running the "Compromise the system" section, I'm publishing at 100Hz on cmd_velocity:
`ros2 topic pub /cmd_vel geometry_msgs/Twist "linear: {x: 0}" -r 100`

But the robot keeps rotating in circle as if no messages were sent.

If I unload the `twist_publisher` component, I can then publish on `/cmd_vel` and command the robot

**Comment by Karsten1987** [comment]
I can confirm that zero does indeed not stop the robot as the twist publisher keeps the robot moving.
However, in terms of security demo, when publishing
```
ros2 topic pub /cmd_vel geometry_msgs/Twist "linear: {x: 0.5}, angular: {z: 0.5}" -r 10
```
the robot does speed up tremendously. So that can be used as usual for visualization.

**Comment by mikaelarguedas** [comment]
Great!

I added https://github.com/Karsten1987/roscon2018/pull/43/commits/a422587f66f1404a5b17cf10169c6e2ead5b58b2 to use this pattern and make the robot go backward

Thanks!
