### ISSUE TITLE
Come up with logo for rosconFR

### ISSUE THREAD

**Issue by mikaelarguedas** [Karsten1987/roscon2018#56]
There doesn't seem to be an official logo for ROSCon FR.

I'd like to not use the logo of another ROSCon to make the talk more "exclusive". In addition keeping he Madrid logo is kind of misleadng as the current code would not compile against ROS2 code from that time.
Coming up with an alternative (made up) logo would be good.
It shouldn't use the "ROSCon" word though as it's a trademark I believe. We could build on top of the 9 dots logo for example.

**Comment by Karsten1987** [comment]
I wouldn’t take it too seriously with the trademark but I can see your point. To that end we should probably also rename the complete repository :D

**Comment by mikaelarguedas** [comment]
> To that end we should probably also rename the complete repository :D

Yeah actually I was thinking of that recently, for both the trademark and the fact that the year is in the name..

What do you think of simply renaming it to `confbot` ?

The redirect should work until (I guess never) another `roscon2018` repo gets created on this org unit

**Comment by Karsten1987** [comment]
To stay consistent with other robot packages I would propose renaming it to `confbot_robot`. That's following the style of `pepper_robot`, `nao_robot`, etc.

**Comment by mikaelarguedas** [comment]
> To stay consistent with other robot packages I would propose renaming it to confbot_robot

:+1: sounds good to me!

**Comment by mikaelarguedas** [comment]
Closing this as the repo got renamed and #59 has merged
